### ISSUE TITLE
Adding new icons packs to Elementor

### ISSUE THREAD

**Issue by ryanlabelle** [ryanlabelle/th-widget-pack#101]
@adiraomj  do you know if we can include custom icon packs like Glyphicons into the Elementor Icon control? Can you find out if their API supports this? We want to be able to add in some new icons packs. 

Thanks!

**Comment by JingwuChen** [comment]
hello ,every how can i add new pack of icons to elementor button,says i want to add the docker icon to one button ,but i can not find the icon in the list ,i have scan the source code of elementor ,but i can not find how to add the new packs of icon in the source code

**Comment by bentalgad** [comment]
If some looks for a way to add icon fonts to the elementor core options this is a great plugin:
https://wordpress.org/plugins/custom-icons-for-elementor/

**Comment by reelism** [comment]
Was this abandoned? Can we add icon packs?

**Comment by suroh001** [comment]
> If some one looks for a way to add icon fonts to the elementor core options this is a great plugin:
> https://wordpress.org/plugins/custom-icons-for-elementor/

This works but for some reason, the icons come out very small for me, is there anyway i can fix this with CSS? my link is http://beta.ahadgroup.co.uk/services

**Comment by smartrashed** [comment]
awesome its working

**Comment by Ninetheme** [comment]
> If some one looks for a way to add icon fonts to the elementor core options this is a great plugin:
> https://wordpress.org/plugins/custom-icons-for-elementor/

don't use this plugin, will slow down your website because of 50MB+ database tables
