### ISSUE TITLE
Elementor Templates

### ISSUE THREAD

**Issue by teaganm** [ryanlabelle/th-widget-pack#118]
Hi Adi,

Elementor includes its own "templates" feature that imports content into the page builder. We're intending to make use of it so that customers can import whole pages, and also import partial sections of pages.

Here's a quick video showing where it is: https://cl.ly/1X1d2L0b383M

I'm able to create my own templates, and they get added into the "My Templates" tab - but we're wondering if it could be possible to:

1) Create an additional tab that comes before the "Predesigned Templates" section and title it "Theme Templates" - https://cl.ly/393h3H061F3x

2) Display the templates in the same visual way as the Predesigned Templates, rather than in a list like the "My Templates" section

Are you able to see if we can tap into that functionality?

Let me know if anything is unclear.

Thanks!

**Comment by adiraomj** [comment]
The elementor guys have said they will be adding this functionality soon.
https://github.com/pojome/elementor/issues/417

I could not find another way to add it in the same visual way as the Predesigned templates. Tried a few hooks, but they did not work well.

**Comment by ryanlabelle** [comment]
Thanks. That would be awesome.

**Comment by sourabhgarg01** [comment]
Any update on this feature? Are we able to add custom templates in "Predesigned Templates"?
