### ISSUE TITLE
Extra space at top of Blog template pages

### ISSUE THREAD

**Issue by teaganm** [ryanlabelle/th-widget-pack#147]
When using either the standard blog template or the masonry blog template, there is extra space at the top just below the page title - the space is from the output of the Content Editor section.

This issue didn't come up in our old framework b/c we didn't output the Content Editor on these templates - but now that Elementor is used for the page headers, we of course want to offer the option to have Content Editor content above the template output.

As we discussed, if we can make it so that the "content-editor" section is only output if there is content added (or if Elementor is enabled) that would be ideal. If that's not possible or is cumbersome to implement, then we can review and find a solution.

**Comment by ryanlabelle** [comment]
Hmm, I'll have to come back to this, I did a have_posts() which should be false but it returns true even when the the_content() is empty. Is there a quick workaround with CSS or is it hacky?

**Comment by ryanlabelle** [comment]
In addition to that, it looks like if I do a pre check for an empty page, Elementor won't work on that page. Strange. Let's talk about this tomorrow. Looks like we might need a css fix. 

@teaganm

**Comment by ryanlabelle** [comment]
Adding .th-editor-empty class if content-editor element is empty, else just leave it as .content-editor.

**Comment by teaganm** [comment]
Great, thanks  👍
