### ISSUE TITLE
Nag notice in Widget Logic

### ISSUE THREAD

**Issue by ryanlabelle** [ryanlabelle/th-widget-pack#148]
As far as I can tell, their is a unique ID for the nag notice. 

#wpchefgadget_alert_lla

https://cl.ly/3y2I353o3u1K

IMHO it's best to just css hide this and then we can put it it to bed. Good?

**Comment by teaganm** [comment]
Looks like it was actually removed in one of the last 2 releases of the plugin. I only see it if I install an older version onto a site.

Added the code to hide it anyway.

**Comment by ryanlabelle** [comment]
Great! Thanks
