### ISSUE TITLE
Elementor widget sample content - Icons need updating

### ISSUE THREAD

**Issue by teaganm** [ryanlabelle/th-widget-pack#151]
Widgets with icons that need updating:

- Service Block = "bus"

- Tour Info Bar
  - 4.5 miles = "compass"
  - 3 hours = "clock-time"
  - 3+ people = "person-plus" 

Or open to suggestion.

**Comment by ryanlabelle** [comment]
Updated service block and tour bar

**Comment by teaganm** [comment]
Looks good 👍
