### ISSUE TITLE
WPML - Hide widgets per active theme.

### ISSUE THREAD

**Issue by ryanlabelle** [ryanlabelle/th-widget-pack#158]
@adiraomj 

We have some logic in place to show / hide certain elements depending on the active theme. You can see this under https://github.com/ryanlabelle/th-widget-pack/blob/WPML/inc/setup.php

The themes are embark, bellevue, stratus, pursuit, and entrepreneur.

I tried to add this logic to https://github.com/ryanlabelle/th-widget-pack/blob/WPML/languages/wpml-translations.php but I had to comment it out because of the class importing / aliases at the top. 

I thought it would be best to send this back to you to see if you wanted to implement this in a specific way.

**Comment by adiraomj** [comment]
Done. Please test.
I have used a switch statement. Can we do the same in the setup.php file? It would be easier to read and manage. :)

**Comment by ryanlabelle** [comment]
For sure :)

**Comment by ryanlabelle** [comment]
Looking good, one issues is the order. They are messed up when using WPML but I can probably fix that. Thanks.

**Comment by ryanlabelle** [comment]
Hi @adiraomj - WPML has been working well, have you used WPML 4.0 yet?
