### ISSUE TITLE
WPML - 500 Server Error when WPML not active

### ISSUE THREAD

**Issue by ryanlabelle** [ryanlabelle/th-widget-pack#159]
@adiraomj 

Some users wont be installing WPML so we'll need to clean up that 500 Server error when WPML is deactivated.

Fatal error: Class 'WPML_Elementor_Module_With_Items' not found in /Users/rl/Sites/embark/wp-content/plugins/th-widget-pack/languages/wpml-slider.php on line 5

**Comment by adiraomj** [comment]
Done. Please test.

**Comment by ryanlabelle** [comment]
Thanks! I'll test tomorrow.

**Comment by ryanlabelle** [comment]
Looks great! Thank you.
