### ISSUE TITLE
Page crashes on update to Elementor 2.7.2

### ISSUE THREAD

**Issue by ergophobe** [ryanlabelle/th-widget-pack#174]
Works fine with Elementor 2.6.8. I upgraded to 2.7.2 and a page crashed. I did a git checkout of Elementor to revert to 2.6.8 and everything seemed to work fine. 

WP 5.2 now sends a sort of stack trace by email. This is what it says (anonymized with "example" instead of username):

Error Details
=============
An error of type E_ERROR was caused in line 269 of the file /home/example/public_html/wp-content/plugins/th-widget-pack/inc/setup.php. Error message: Uncaught TypeError: Argument 1 passed to th_add_custom_controls_elem_post_settings_top() must be an instance of Elementor\Core\DocumentTypes\Post, instance of Elementor\Core\DocumentTypes\Page given, called in /home/example/public_html/wp-includes/class-wp-hook.php on line 288 and defined in /home/example/public_html/wp-content/plugins/th-widget-pack/inc/setup.php:269
Stack trace:
#0 /home/example/public_html/wp-includes/class-wp-hook.php(288): th_add_custom_controls_elem_post_settings_top(Object(Elementor\Core\DocumentTypes\Page), 'document_settin...')
#1 /home/example/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/example/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /home/example/public_html/wp-content/plugins/elementor/includes/compatibility.php(67): do_action('elementor/eleme...', Object(Elementor\Core\DocumentTypes\Page), 'document_settin...', Array)
#4 /home/example/public_html/wp-includes/clas

**Comment by ryanlabelle** [comment]
Please see https://github.com/ryanlabelle/th-widget-pack/pull/175

Thanks for letting us know though.

**Comment by ryanlabelle** [comment]
More info:

This has been fixed in the most recent version of our Page Builder Widget Pack. 

https://themovation.helpscoutdocs.com/article/251-page-builder-widget-pack-current-version

Apparently a bug in the most recent version of Elementor. 

All good now, but let us know if you run into any issues.

Cheers!​

**Comment by ergophobe** [comment]
Thanks Ryan. Strange, but WP is not picking up the new version of Page Builder Widget Pack, so it's updating Elementor, but not PBWP

**Comment by ergophobe** [comment]
Ah, got it. PBWP does not pull update info from WP.org and I had disabled the Bellevue functions that override the WP.org updates, because it was causing problems. Had to re-enable just the one for PBWP then everything updated together.

**Comment by ryanlabelle** [comment]
Thanks. Correct, it's not part of the WP repo. We host it on github and have our own private repo, but if you are using Bellevue version 3.2.2, you should see the update for PBWP pop up under wp dash / updates or wp dash / plugins.

Glad it worked out. 

You can also reach out to us on our support system here: https://themovation.ticksy.com/

or via our author profile here: https://themeforest.net/user/themovation

**Comment by markb999** [comment]
I'm having the same issue with Bellevue Version: 3.2.7 By Themovation - an updated version for the Page Builder Widget Pack is not available as an option in the plugins folder? It seems to be stuck on Page Builder Widget Pack is 1.5.6
How can I force it to show me the updated version?

**Comment by ryanlabelle** [comment]
Hi Mark, can you please create a ticket for us? 

https://themovation.ticksy.com/

**Comment by markb999** [comment]
> Hi Mark, can you please create a ticket for us?
> 
> https://themovation.ticksy.com/

Unfortunately not. The theme was purchased late last year for a client - in the hospitality industry. Because of the Covid-19 situation they parked the whole project for a few months - so the 6 months support is now up. I hoped you might have some idea what is preventing WP from showing the updated plugin and be prepared to offer some suggestions here.

**Comment by ryanlabelle** [comment]
Hi Mark, no worries. Just sign in to your ThemeForest account and send us a message on our Profile page. 

https://themeforest.net/user/Themovation

We'll help get you all sorted out.

**Comment by markb999** [comment]
> Hi Mark, no worries. Just sign in to your ThemeForest account and send us a message on our Profile page.
> 
> https://themeforest.net/user/Themovation
> 
> We'll help get you all sorted out.

Thanks Ryan, I'll do that.
