### ISSUE TITLE
Page Settings not reloading editor after changing options!

### ISSUE THREAD

**Issue by beratgashi** [ryanlabelle/th-widget-pack#176]
Hi,

With the newest elementor update the - jQuery method update is soft deprecated since 2.9.0 - in console log it says use `$e.run( 'document/save/update' )` instead, i think that because of this Editor is not reloading after changing options of your plugin!

**Comment by ryanlabelle** [comment]
Amazing! Thanks for sharing. We'll get this updated asap. :)

**Comment by ryanlabelle** [comment]
We have a fix coming out for this soon. Thanks for letting us know.

**Comment by beratgashi** [comment]
It's been about a month now and nothing came out!

**Comment by ryanlabelle** [comment]
Hey there! Are you getting update via our github? We release through the WP Dashboard / Plugins (live updates). 

If you prefer to get this via the github repo, I just merged our develop branch to master. 

cheers!

**Comment by beratgashi** [comment]
@ryanlabelle thank you, i don't know how i missed the update in the WP Dashboard though!
