### ISSUE TITLE
Validate Sanitize escape All widgets

### ISSUE THREAD

**Issue by ryanlabelle** [ryanlabelle/th-widget-pack#91]
Themeforest is pretty strict when it comes to validating, escaping , sanitizing all input / outputs. Mostly they want to make sure that any thing echo $var is getting escaped. Can you please review all widgets and makes sure to use the WordPress escaping tools provided as late as possible in the output? 

https://vip.wordpress.com/documentation/vip/best-practices/security/validating-sanitizing-escaping/#escaping-securing-output

and

https://vip.wordpress.com/documentation/vip/best-practices/security/validating-sanitizing-escaping/#always-escape-late

**Comment by adiraomj** [comment]
Hey.. Thanks for the links.. Really liked the last one.

I have not escaped the variables in the **option-tree** folder. Should I do them too?

**Comment by ryanlabelle** [comment]
Option tree can be left alone, thanks for asking :)

**Comment by ryanlabelle** [comment]
I think we are good now. :) Closing this one.
